// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChstndHyV_oqBH305sySNre2sEYMXeAIg',
    appId: '1:952888872607:web:0403505f945cd244d75caa',
    messagingSenderId: '952888872607',
    projectId: 'chat-connect-b9f01',
    authDomain: 'chat-connect-b9f01.firebaseapp.com',
    storageBucket: 'chat-connect-b9f01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChstndHyV_oqBH305sySNre2sEYMXeAIg',
    appId: '1:952888872607:android:0403505f945cd244d75caa',
    messagingSenderId: '952888872607',
    projectId: 'chat-connect-b9f01',
    storageBucket: 'chat-connect-b9f01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChstndHyV_oqBH305sySNre2sEYMXeAIg',
    appId: '1:952888872607:ios:0403505f945cd244d75caa',
    messagingSenderId: '952888872607',
    projectId: 'chat-connect-b9f01',
    storageBucket: 'chat-connect-b9f01.firebasestorage.app',
    iosClientId: '952888872607-ios-client-id',
    iosBundleId: 'com.example.tuneupTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChstndHyV_oqBH305sySNre2sEYMXeAIg',
    appId: '1:952888872607:macos:0403505f945cd244d75caa',
    messagingSenderId: '952888872607',
    projectId: 'chat-connect-b9f01',
    storageBucket: 'chat-connect-b9f01.firebasestorage.app',
    iosClientId: '952888872607-macos-client-id',
    iosBundleId: 'com.example.tuneupTask',
  );
}
